- name: Install Zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Configure Zabbix agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: '0644'
  notify: restart zabbix-agent

- name: Ensure zabbix-agent is enabled and running
  service:
    name: zabbix-agent
    state: started
    enabled: yes
