- hosts: web
  become: yes
  roles:
    - nginx
    - filebeat
    - zabbix_agent

- hosts: elastic
  become: yes
  roles:
    - elasticsearch

- hosts: kibana
  become: yes
  roles:
    - kibana

- hosts: zabbix
  become: yes
  roles:
    - zabbix_agent
